Iincho/urls.py
from django.conf.urls import include, url, patterns
from django.conf import settings
from django.contrib import admin
import articles.urls
import accounts.urls
import attachments.urls
import categories.urls
import web.urls

urlpatterns = [
    url(r'^$', include(web.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^articles/', include(articles.urls, namespace='articles')),
    url(r'^accounts/', include(accounts.urls, namespace='accounts')),
    url(r'^attachments/', include(attachments.urls, namespace='attachments')),
    url(r'^categories/', include(categories.urls, namespace='categories')),
]

if settings.DEBUG :
    urlpatterns += patterns(
        '', url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }
        ),
    )
    urlpatterns += patterns(
        '', url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }
                ),
    )

articles/urls.py
from django.conf.urls import url
from .views import ArticleDetailAndCreateCommentView, ArticleCreateView, ArticleListView, ArticleUpdateView, ArticleDeleteView, OwnersArticleListView
from .views import delete_comment


urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='list'),
    url(r'^owner/(?P<owner_id>\d+)/$', OwnersArticleListView.as_view(), name='owners_articles'),
    url(r'^(?P<pk>\d+)/$', ArticleDetailAndCreateCommentView.as_view(), name='detail'),
    url(r'^new/$', ArticleCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/edit/$', ArticleUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', ArticleDeleteView.as_view(), name='delete'),
    url(r'^(?P<article_id>\d+)/comment_delete/$', delete_comment, name='comment_delete'),
    url(r'^select_template/$',
        'articles.views.select_template', name='select_template'),
]

web/urls.py
from django.conf.urls import url
from .views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
]

articles/models.py
from django.db import models
from core.models import TimeStampedModel
from django.contrib.auth.models import User
from categories.models import Category


class Article(TimeStampedModel):
    owner = models.ForeignKey(User)
    title = models.TextField(default='no title')
    body = models.TextField()
    category = models.ForeignKey(Category)

    def __str__(self):
        return self.title


class Comment(TimeStampedModel):
    user = models.ForeignKey(User)
    article = models.ForeignKey(Article)
    body = models.TextField()

    def __str__(self):
        return self.body


class Tag(TimeStampedModel):
    article = models.ForeignKey(Article)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'id': 'article-title',
                   'class': 'form-control',
                   'placeholder': 'category1/category2/.../タイトル #tag1, tag2'}
        )
    )

    body = forms.CharField(
        label='article-body',
        widget=forms.Textarea(
            attrs={'id': 'article-code', }
        )
    )

    templates = forms.ChoiceField(
        required=False,
        widget=forms.Select(
            attrs={'class': 'form-control', }
        )
    )

    class Meta:
        model = Article
        fields = ['body', ]


class CommentForm(forms.ModelForm):
    body = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control', 'placeholder': 'コメント'}
        )
    )

    class Meta:
        model = Comment
        fields = ['body', ]

articles/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.views.decorators.http import require_POST, require_GET
from .models import Article, Comment, Tag
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse, reverse_lazy
from .forms import ArticleForm, CommentForm
from braces.views import LoginRequiredMixin
from categories.views import CategoryListViewMixin
from core.mixins import TagSearchMixin, CategorySearchMixin
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.conf import settings
from .utils import rebuild_edit_title, rebuild_edit_title_without_template_prefix, template_formatting
import categories
from articles.mixins import ArticleListMixin, ArticleSearchMixin, IsOwnerMixin, SetTagsAndCategorizeMixin


class ArticleListView(ArticleListMixin, ArticleSearchMixin,
                      CategorySearchMixin, TagSearchMixin,
                      LoginRequiredMixin, CategoryListViewMixin, ListView):
    model = Article
    template_name = 'article_list.jinja2'
    paginate_by = 10


class OwnersArticleListView(ArticleListMixin, LoginRequiredMixin, ListView):
    model = Article
    template_name = 'article_list.jinja2'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context_data = super(OwnersArticleListView, self).get_context_data(**kwargs)
        context_data['owner'] = User.objects.get(pk=self.kwargs['owner_id']).username
        return context_data


class ArticleDetailAndCreateCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'article_detail.jinja2'

    def get_success_url(self):
        return reverse('articles:detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.article = Article.objects.get(pk=self.kwargs['pk'])
        return super(ArticleDetailAndCreateCommentView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super(ArticleDetailAndCreateCommentView, self).get_context_data(**kwargs)
        article = Article.objects.get(pk=self.kwargs['pk'])
        context_data['article'] = article
        context_data['tags'] = Tag.objects.filter(article=article)
        context_data['category'] = \
            article.category.name if article.category.name != categories.NOT_CATEGORISED else ''
        context_data['comments'] = Comment.objects.filter(article=self.kwargs['pk']).select_related('user',
                                                                                                    'user__profile').order_by(
            'modified')
        return context_data


class ArticleEditMixin(object):
    model = Article
    template_name = 'article_form.jinja2'
    form_class = ArticleForm


    def get_form(self, form_class=None):
        form = super(ArticleEditMixin, self).get_form()
        template_choices = [('', 'テンプレート')]
        template_articles = Article.objects.filter(category__name__startswith='template/')

        template_choices += \
            [(x.id, rebuild_edit_title_without_template_prefix(x)) for x in template_articles]

        form.fields['templates'].choices = template_choices
        return form


class ArticleCreateView(LoginRequiredMixin, ArticleEditMixin, SetTagsAndCategorizeMixin, CreateView):
    def get_initial(self):
        data = super(ArticleCreateView, self).get_initial()

        path = self.request.GET.get('path')  # type:str
        if path:
            if not path.endswith('/'):
                path += '/'
            data['title'] = path
        return data

    def get_success_url(self):
        return reverse('articles:detail', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        return super(ArticleCreateView, self).form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, ArticleEditMixin, SetTagsAndCategorizeMixin,
                        IsOwnerMixin, UpdateView):
    def get_success_url(self):
        if self._object:
            return reverse('articles:detail', kwargs={'pk': self._object.id})
        else:
            return reverse('articles:list')

    def get_object(self, **kwargs):

        # 既に生成済みの場合は，そのオブジェクトを返却する(dispatchでも呼び出すため複数回呼ばれる）
        if not hasattr(self, '_object'):
            self._object = super(ArticleUpdateView, self).get_object(**kwargs)

        return self._object

    def get_initial(self):
        data = super(ArticleUpdateView, self).get_initial()
        article = self.get_object()
        data['title'] = rebuild_edit_title(article)

        return data


class ArticleDeleteView(IsOwnerMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('articles:list')
    template_name = "article_confirm_delete.jinja2"


@require_POST
def delete_comment(request, article_id):
    comment_id = request.POST.get('comment_id')
    if comment_id:
        obj = get_object_or_404(Comment, pk=comment_id)
        if obj.user == request.user or request.user.is_superuser:
            obj.delete()
        else:
            messages.warning(
                request, "You are not allowed to edit this comment")

    return redirect('articles:detail', article_id)


@require_GET
def select_template(request):
    article_id = request.GET.get('article')

    article = get_object_or_404(Article, pk=article_id)
    title = rebuild_edit_title_without_template_prefix(article)

    result = {}
    result['title'] = template_formatting(request, title)
    result['body'] = template_formatting(request, article.body)
    return JsonResponse(result)

articles/templates/article_confirm_delete.jinja2
{% extends "base.jinja2" %}

{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="" method="post">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        <h1>削除確認</h1>
        {{ object.title }}
        <input type="submit" value="削除" onclick="setDisable(this)" />

    </form>
{% endblock %}

articles/templates/article_detail.jinja2
{% extends "base.jinja2" %}
{% import "basic_macros.jinja2" as b_macro with context %}
{% import "categories/macros.jinja2" as c_macro %}

{% block head %}
    <script src="{{ static('markdown-editor/js/markdown-it.js') }}" xmlns="http://www.w3.org/1999/html"></script>
    <script src="{{ static("markdown-editor/js/markdown-it-footnote.js") }}"></script>
    <script src="{{ static("markdown-editor/js/highlight.pack.js") }}"></script>
    <script src="{{ static("markdown-editor/js/emojify.js") }}"></script>
    <link rel="stylesheet" href="{{ static("markdown-editor/css/default.css") }}">
    <link rel="stylesheet" href="{{ static("articles/article.css") }}">
{% endblock %}

{% block content %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="article_header">
        <div class="category_list">
            {{ c_macro.make_nodes_link(article.category.name, 'breadcrumb') }}
        </div>

        <div class="pull-right">
           <span>
               <img class="owner_icon" src="{{ bas_macro.user_icon_url(article.owner) }}" alt="owner-photo" />
               <a href="{{ url('articles:owners_articles', article.owner.id)  }}">
               {{ article.owner.username }}</a> が
           </span>
            <span>{{ article.created | datetimeformat('%Y/%m/%d') }}に投稿</span>
        </div>
        <h1 id="detail_title">
            {{ article.title }}
            {% if article.owner.id == user.id or user.is_superuser %}
                <a href="{{ url('articles:update', article.id) }}" class="btn btn-md btn-default">編集</a>
                <button type="button" class="btn btn-default" onclick="delete_article();" data-toggle="modal" data-target="#delete_article_confirm">削除</button>

            {% endif %}
        </h1>
        <div class="article_tags">
            <ul>
            {% for tag in tags %}
                <li class="li_tag"><a href="{{ url('articles:list') }}?tag={{ tag.name | urlencode }}">{{ tag.name }}</a></li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <div class="article_body">
        <div id="raw_body" style="display: none;">{{ article.body }}</div>
        <div id="out" class="editor-textarea"></div>
    </div>

    {{ b_macro.confirm_modal(modal_id='delete_article_confirm', btn_class="btn-danger") }}
    <form id="delete_form" action="{{ url('articles:delete', article.id) }}" method="post">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
    </form>

    {# コメント #}
    <div class="comments">
        <div>
            <h2><span class="glyphicon glyphicon-comment" style="margin-right:5px"></span>comments</h2>
        </div>
        {% for comment in comments %}
            <div class="media">
                <div class="media-left">
                    <img class="user_icon" src="{{ b_macro.user_icon_url(comment.user) }}" alt="comment-user-photo" />
                </div>
                <div class="media-body">
                    <div class="comment_status">
                        <a href="{{ url('articles:owners_articles', comment.user.id) }}">{{ comment.user.username }}</a>
                        <p class="pull-right">{{ comment.created | datetimeformat() }}
                            <span>
                                {% if comment.user.id == user.id or user.is_superuser %}
                                    <a href="#" onclick="delete_comment(this)" data-label="{{ comment.id }}"
                                         data-toggle="modal" data-target="#delete_comment_confirm">削除</a>
                                {% endif %}
                            </span>
                        <p>
                    </div>
                    <div class="comment_body md_comment">{{ comment.body }}</div>
                </div>
            </div>
        {% endfor %}
        {# コメント投稿 #}
        <div class="media">
            <div class="media-left">
                <img class="user_icon" src="{{ b_macro.user_icon_url(user) }}" alt="comment-user-photo" />
            </div>
            <div class="media-body">
                <div class="comment_status">
                    <h4 class="media-heading">コメントを投稿</h4>
                </div>
                <div class="comment_body">
                    <form method="post" action="">
                        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                        {{ form.body.errors }}
                        <div>
                            {{ form.body }}
                        </div>
                        <input type="submit" class="btn btn-md btn-primary pull-right" onclick="setDisable(this)" />
                    </form>
                </div>
            </div>
        </div>
    </div>

    {{ b_macro.confirm_modal(modal_id='delete_comment_confirm', btn_class="btn-danger") }}
    <form id="del_comment_form" method="post" action="{{ url("articles:comment_delete", article.id) }}">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        <input type="hidden" id="del_comment_id" name="comment_id" />
    </form>
{% endblock %}

{% block body_script %}
    <script src="{{ static('articles/markdown.js') }}"></script>
    <script>
        emojify.setConfig({img_dir:'{{  static('markdown-editor/emoji') }}'});
        $(function(){
            var md = new markdownRender();
            var out = document.getElementById('out');
            out.innerHTML = md.render($('#raw_body').text());
            emojify.run(out);

            $('.md_comment').each(function(){
                var raw = $(this).text();
                var md_txt = md.render(raw);
                $(this).html(md_txt);
                emojify.run($(this)[0]);
            });

            //モーダル設定
            $('#delete_comment_confirm').find('.modal-message').text('コメントを削除しますか？');

        });

        // 記事削除
        function delete_article(){
            var confirm = $('#delete_article_confirm')
            confirm.find('.modal-message').text('投稿: {{ article.title }} を削除しますか？');
            confirm.find('.modal-submit').click(function(){
                $('#delete_form').submit();
            });
        }
        // コメント削除
        function delete_comment(a){
            $('#del_comment_id').val($(a).attr("data-label"));
            $('#delete_comment_confirm').find('.modal-submit').click(function(){
                $('#del_comment_form').submit();
            });
        }

    </script>

{% endblock %}

articles/templates/article_form.jinja2
{% extends "base.jinja2" %}
{% import "ajax_macros.jinja2" as ajax_macro %}

{% block head %}
    <script src="{{ static('markdown-editor/js/markdown-it.js') }}"></script>
    <script src="{{ static("markdown-editor/js/markdown-it-footnote.js") }}"></script>
    <script src="{{ static("markdown-editor/js/highlight.pack.js") }}"></script>
    <script src="{{ static("markdown-editor/js/emojify.js") }}"></script>
    <script src="{{ static("markdown-editor/codemirror/lib/codemirror.js") }}"></script>
    <script src="{{ static("markdown-editor/codemirror/overlay.js") }}"></script>
    <script src="{{ static("markdown-editor/codemirror/xml/xml.js") }}"></script>
    <script src="{{ static("markdown-editor/codemirror/markdown/markdown.js") }}"></script>
    <script src="{{ static("markdown-editor/codemirror/gfm/gfm.js") }}"></script>
    <script src="{{ static("markdown-editor/codemirror/javascript/javascript.js") }}"></script>
    <script src="{{ static("markdown-editor/codemirror/css/css.js") }}"></script>
    <script src="{{ static("markdown-editor/codemirror/htmlmixed/htmlmixed.js") }}"></script>
    <script src="{{ static("markdown-editor/codemirror/lib/util/continuelist.js") }}"></script>
    <script src="{{ static("markdown-editor/codemirror/addon/searchcursor.js") }}"></script>
    <script src="{{ static("markdown-editor/js/rawinflate.js") }}"></script>
    <script src="{{ static("markdown-editor/js/rawdeflate.js") }}"></script>
    <script src="{{ static("js/string_utils.js") }}"></script>
    <link rel="stylesheet" href="{{ static("markdown-editor/codemirror/lib/codemirror.css") }}">
    <link rel="stylesheet" href="{{ static("markdown-editor/css/default.css") }}">
    <link rel="stylesheet" href="{{ static("articles/article.css") }}">
    <link rel="stylesheet" href="{{ static("markdown-editor/css/base16-light.css") }}">
    <script src="{{ static("file_upload/js/vendor/jquery.ui.widget.js") }}"></script>
    <script src="{{ static("file_upload/js/jquery.iframe-transport.js") }}"></script>
    <script src="{{ static("file_upload/js/jquery.fileupload.js") }}"></script>
    <link rel="stylesheet" href="{{ static("file_upload/css/jquery.fileupload.css") }}">
<style>
    .container {width:auto;}
</style>
{% endblock %}

{% block content %}
    <div class="main-container">
    {% if form.errors %}
        <div class="row">
            <div class="col-md-6">
                <div class="alert alert-danger" role="alert">
                    {{ form.non_field_errors() }}
                    {% for field in form %}
                        {% if field.errors %}
                            {{ field.label }}
                            <ul>
                                {% for error in field.errors %}
                                    <li> {{ error|escape }} </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-6">
            <form action="" method="post">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">

                <div class="errors">
                    {{ form.title.errors }}
                </div>
                <div class="editor-header">
                    {{ form.templates }}
                    {{ form.title }}
                </div>
                <div id="editor_area" class="editor-textarea">
                    {{ form.body }}
                </div>
                <div class="row editor-footer">
                    <div>
                        <button id="btn_post" class="btn btn-md btn-primary pull-right" onclick="setDisable(this)">投稿</button>
                    </div>
                </div>
            </form>
            <div class="uploader">
                <div>
                    <span class="fileinput-button">
                        <img class="upload_icon" src="{{ static('articles/images/up_picture.png') }}" />
                        <input type="file" id="fileupload" name="file" />
                    </span>
                </div>
            </div>
        </div>

        <div class="col-md-6 hidden-sm hidden-xs" style="height:100%">
            <div class="editor-preview">
                <div class="editor-preview-header">
                    <h1 id="title-out"></h1>
                </div>
                <div id="out" class="editor-textarea"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block body_script %}
    <script>
        {{ ajax_macro.django_ajax_init() }}
        emojify.setConfig({img_dir:'{{  static('markdown-editor/emoji') }}'});

        var upload_helper = function(){
            var imageType = /^image\/(gif|jpe?g|png)$/i;
            var urlPrefix = 'now uploading... '
            return {
                added : function(fileType) {
                    var isImage = (fileType && imageType.test(fileType));
                    var prefix = isImage ? '!' : '';
                    var uniqueStr = getUniqueStr();

                    editor.replaceRange(prefix + '['+ uniqueStr + '](' +  urlPrefix + uniqueStr + ')\n',
                            CodeMirror.Pos(editor.getCursor().line, editor.getCursor().ch));
                    return uniqueStr;
                },
                uploaded : function(target, fileName, fileUrl){
                    if(!target) return;
                    // アップロードpathに置換
                    var searchCursor = editor.getSearchCursor(target);
                    if(fileName && searchCursor.findNext()){
                        searchCursor.replace(fileName);
                    }
                    searchCursor = editor.getSearchCursor(urlPrefix + target);
                    if(fileUrl && searchCursor.findNext()){
                        searchCursor.replace(fileUrl);
                    }
                }
            };
        }();

        // file-upload
        $(function () {
            'use strict';

            // Change this to the location of your server-side upload handler:
            var url='';
            url = '{{ url('attachments:upload_file_jq') }}';
            $('#fileupload').fileupload({
                timeout: 20000,
                url: url,
                dataType: 'json',
                dropZone: $('#editor_area'),
                drop: function (e, data) {
                    if(!data.upload_canceled && data.files.length > 3){
                        data.upload_canceled = true;
                        alert("一度にアップロード可能なファイルは3つまでです．")
                    }
                },
                add: function(e, data){
                    if(data.upload_canceled) return;

                    var uploadErrors = [];
                    var acceptFileTypes = /^((image\/(gif|jpe?g|png))|(application\/(pdf|x-tex|postscript))|(text\/(tab-separated-values|plain|xml)))$/i;
                    var fileType = data.files[0]['type'];

                    if(!acceptFileTypes.test(fileType)) {
                        uploadErrors.push(data.files[0].name + ' is not an accepted file type');
                    }
                    if(data.files[0]['size'] && data.files[0]['size'] > 5242880) {
                        uploadErrors.push(data.files[0].name + ' filesize is too big');
                    }
                    if(uploadErrors.length > 0) {
                        alert(uploadErrors.join("\n"));
                    } else {
                        data.files[0].unique_id = upload_helper.added(fileType);
                        data.submit();
                    }
                },
                done: function (e, data) {
                    if (data.result.status == 'success'){
                        upload_helper.uploaded(data.files[0].unique_id, data.result.file_name, data.result.file_url);
                    }else{
                        if(data.result.messages){
                            alert(data.result.messages.join("\n"));
                        }else{
                            alert('failed upload.');
                        }
                    }

                },
                fail: function(jqXHR, status, err) {
                    alert('failed upload.');
                }
            }).prop('disabled', !$.support.fileInput)
            .parent().addClass($.support.fileInput ? undefined : 'disabled');

            $("#id_templates").change(select_template);
        });

        function select_template(){
            if($(this).val() == "") return false;

            $.ajax({
                type: "GET",
                url: '{{ url('articles:select_template') }}',
                data:{'article': $(this).val()},
                dataType: 'json',
                timeout: 10000
            }).done(function(data){
                console.log(data);
                $('#article-title').val(data.title);
                editor.setValue(data.body);
                editor.clearHistory();
            })
            .fail(function(){
                alert('failed to load template.');
            });
        }
    </script>
    <script src="{{ static('articles/markdown.js') }}"></script>
    <script src="{{ static('articles/editor.js') }}"></script>

{% endblock %}

articles/templates/article_list.jinja2
{% extends "base.jinja2" %}
{% import "article_macros.jinja2" as articro with context %}

{% block content %}
    <div class="list_header">
        {% if owner %}
            <h2>{{ owner }}の投稿</h2>
        {% else %}
            <h2>{{ request.GET.get('query') }} 投稿一覧</h2>
        {% endif %}
    </div>
    {{ articro.article_list() }}
{% endblock %}